### ISSUE TITLE
Set `EditURL` in Documenter

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/PlutoStaticHTML.jl#61]
Thanks to https://github.com/JuliaManifolds/Manopt.jl/blob/00aa4a8f833b4052bfa97ca8bcf7956c3286639c/docs/make.jl#L62-L64:

    ```@meta
    EditURL = "$(pluto_src_folder)$(f).jl"
    ```

**Comment by rikhuijzer** [comment]
Fixed in f484a06.

It was a bit tricky to get the EditURL right because it requires knowing the path and the default branch and because `PlutoStaticHTML.jl` makes no assumptions about where you store the notebooks. I've tried to automatically figure them out. Let's hope it works.

**Comment by rikhuijzer** [comment]
cc @kellertuer @sethaxen

**Comment by kellertuer** [comment]
I do not directly get all the details of the code but the idea: nice!

Does it always add the edit url? That is: Should I remove that from my code then, now, when updating?
(I am still missing two notebooks in reworking my tutorials, but so far everything is going fine :) )

**Comment by rikhuijzer** [comment]
> Does it always add the edit url? 

Only when using `output_format=documenter_output` which I think you are not

**Comment by kellertuer** [comment]
It is what I am running, 

https://github.com/JuliaManifolds/Manopt.jl/blob/d3619b5bd165d1914ac4480bb84ba118e9f79679/docs/make.jl#L39-L44

so then it might be interesting for me what my current code should be updated to and whether the automatic determination of the URL does work.
